version: '3.8'
services:
  postgres:
    image: postgres:13
    container_name: lora_postgres
    environment:
      POSTGRES_DB: lora_monitoring
      POSTGRES_USER: lora_user
      POSTGRES_PASSWORD: lora_password
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres_data:/var/lib/postgresql/data
    restart: unless-stopped